apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: portal
spec:
  destination:
    name: ''
    namespace: portal
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/arup1221/private-registry.git'  
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
