---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myplugin-deployment
  namespace: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myplugin
  template:
    metadata:
      labels:
        app: myplugin
    spec:
      containers:
      - name: myplugin-container
        image: localhost:5000/arup1221/myplugin:0.1
        ports:
        - containerPort: 80

---
